/**
 * Public identifier used by the runtime for externally supplied objects.
 *
 * The runtime does not interpret identifier contents. Callers decide how IDs
 * are created and persisted so this package stays independent of business
 * domains, storage systems, and command interfaces.
 */
export type RuntimeId = string;

/**
 * Supported lifecycle states for APOS runtime execution.
 *
 * These states mirror the Kernel workflow language at a structural level only.
 * They are status markers, not implementations of validation, generation, QA,
 * or release behavior.
 */
export type RuntimeStatus =
  | "pending"
  | "analyzed"
  | "work_package_created"
  | "agent_assigned"
  | "running"
  | "completed"
  | "failed";

/**
 * Minimal request envelope accepted by the runtime.
 *
 * The `payload` is intentionally unknown. Business objects, vertical-pack
 * knowledge, and command-specific inputs must remain outside the runtime
 * skeleton until dedicated contracts exist for them.
 */
export interface RuntimeRequest {
  /** Stable request identifier supplied by the caller. */
  readonly id: RuntimeId;

  /** Human-readable intent that describes what the caller wants APOS to do. */
  readonly intent: string;

  /** Optional opaque data for future runtime integrations. */
  readonly payload?: unknown;
}

/**
 * Structural analysis result produced before work-package creation.
 *
 * Analysis currently records runtime metadata only. It does not classify
 * business intent, select patterns, call LLMs, or infer missing domain facts.
 */
export interface AnalysisResult {
  /** Unique analysis identifier generated by the runtime. */
  readonly id: RuntimeId;

  /** Original request that was analyzed. */
  readonly request: RuntimeRequest;

  /** Current runtime lifecycle state for the analysis. */
  readonly status: Extract<RuntimeStatus, "analyzed">;

  /** Ordered notes describing runtime-only decisions. */
  readonly notes: readonly string[];
}

/**
 * Unit of work passed between runtime orchestration and agent execution.
 *
 * Work packages deliberately contain no generator output, validator result, or
 * business content. They are coordination records that later layers can enrich
 * when those layers are implemented.
 */
export interface WorkPackage {
  /** Unique work-package identifier generated by the runtime. */
  readonly id: RuntimeId;

  /** Analysis that justified creation of this work package. */
  readonly analysis: AnalysisResult;

  /** Current runtime lifecycle state for the work package. */
  readonly status: Extract<RuntimeStatus, "work_package_created" | "agent_assigned" | "running" | "completed" | "failed">;

  /** Agent currently assigned to the package, if assignment has occurred. */
  readonly assignedAgent?: AgentAssignment;
}

/**
 * Agent descriptor accepted by the runtime.
 *
 * The runtime treats agents as externally defined capabilities. This prevents
 * the skeleton from embedding prompts, LLM clients, business responsibilities,
 * or role-specific behavior.
 */
export interface RuntimeAgent {
  /** Stable agent identifier supplied by the caller. */
  readonly id: RuntimeId;

  /** Display name used for reports and diagnostics. */
  readonly name: string;

  /** Optional capabilities declared by the caller for future routing logic. */
  readonly capabilities?: readonly string[];
}

/**
 * Runtime record linking an agent to a work package.
 *
 * Assignment is bookkeeping only. It does not execute the agent, call an LLM,
 * or decide whether the agent is semantically appropriate for the work.
 */
export interface AgentAssignment {
  /** Unique assignment identifier generated by the runtime. */
  readonly id: RuntimeId;

  /** Assigned agent metadata. */
  readonly agent: RuntimeAgent;

  /** Work-package identifier receiving the assignment. */
  readonly workPackageId: RuntimeId;
}

/**
 * Result returned by `Orchestrator.run`.
 *
 * The run report is intentionally limited to lifecycle metadata. Real APOS
 * assets, files, validation results, QA reports, and repair loops belong in
 * future implementations built on top of this foundation.
 */
export interface RuntimeReport {
  /** Unique run identifier generated by the runtime. */
  readonly id: RuntimeId;

  /** Final runtime status for this skeletal execution. */
  readonly status: Extract<RuntimeStatus, "completed" | "failed">;

  /** Work package that was passed into the run step. */
  readonly workPackage: WorkPackage;

  /** Ordered runtime events emitted by the skeleton. */
  readonly events: readonly RuntimeEvent[];
}

/**
 * Simple runtime event used to make orchestration observable without side
 * effects. Events are plain data so callers can log, persist, or ignore them.
 */
export interface RuntimeEvent {
  /** Runtime lifecycle state associated with the event. */
  readonly status: RuntimeStatus;

  /** Human-readable description of the structural step that occurred. */
  readonly message: string;
}
