/**
 * Shared runtime contracts for the APOS Runtime Core.
 *
 * This module is the single dependency that every runtime module is allowed to
 * import. Concrete modules (orchestrator, dispatcher, loader, workflow, report)
 * never import each other directly. They depend only on the data shapes and
 * port interfaces declared here, which keeps every module independent and lets
 * the orchestrator wire collaborators together through interfaces rather than
 * concrete classes (Dependency Inversion Principle).
 *
 * Nothing in this file performs business logic, reads configuration, or calls a
 * language model. It defines structure only.
 */

/**
 * Opaque identifier used across the runtime.
 *
 * The runtime never parses identifier contents; callers and factories decide
 * how IDs are shaped so the package stays independent of storage and tracing
 * systems.
 */
export type RuntimeId = string;

/**
 * Factory that produces runtime identifiers from a semantic prefix.
 *
 * Injecting a single factory lets the orchestrator share one ID strategy across
 * every collaborator without any module embedding its own implementation, which
 * avoids duplication and keeps ID generation deterministic in tests.
 */
export type IdFactory = (prefix: string) => RuntimeId;

/**
 * Lifecycle states a runtime task may occupy.
 *
 * These are structural status markers only. They do not encode validation,
 * generation, QA, or release semantics.
 */
export type TaskState =
  | "pending"
  | "assigned"
  | "running"
  | "completed"
  | "failed";

/**
 * Caller-supplied request envelope entering the runtime.
 *
 * `payload` is intentionally `unknown`. Business objects and command-specific
 * inputs stay outside the runtime until dedicated contracts exist for them.
 */
export interface RuntimeRequest {
  /** Stable request identifier supplied by the caller. */
  readonly id: RuntimeId;

  /** Human-readable description of what the caller wants APOS to do. */
  readonly intent: string;

  /**
   * Capability the work requires, used by the dispatcher for routing.
   *
   * This is a structural tag, not a business rule. When omitted the dispatcher
   * falls back to a deterministic default selection strategy.
   */
  readonly requiredCapability?: string;

  /** Optional opaque data reserved for future runtime integrations. */
  readonly payload?: unknown;
}

/**
 * Coordination record describing a unit of runtime work.
 *
 * A work package carries only routing metadata and the originating request. It
 * never contains generated assets, validator findings, or business content.
 */
export interface WorkPackage {
  /** Unique work-package identifier generated by the runtime. */
  readonly id: RuntimeId;

  /** Request that produced this work package. */
  readonly request: RuntimeRequest;

  /** Capability required to handle the package, if the request declared one. */
  readonly requiredCapability?: string;
}

/**
 * Externally defined agent that can receive work packages.
 *
 * Agents are opaque capability holders. The runtime does not construct prompts,
 * hold model clients, or encode any role behavior here.
 */
export interface AgentDescriptor {
  /** Stable agent identifier supplied by the caller. */
  readonly id: RuntimeId;

  /** Display name used in reports and diagnostics. */
  readonly name: string;

  /** Capability tags the dispatcher matches against work packages. */
  readonly capabilities: readonly string[];
}

/**
 * Result of routing a work package to an agent.
 *
 * Assignment is pure bookkeeping. It does not start the agent or call an LLM.
 */
export interface AgentAssignment {
  /** Unique assignment identifier generated by the runtime. */
  readonly id: RuntimeId;

  /** Work package that was routed. */
  readonly workPackageId: RuntimeId;

  /** Agent selected to receive the work package. */
  readonly agentId: RuntimeId;

  /** Structural reason describing why this agent was selected. */
  readonly reason: string;
}

/**
 * Document loaded from disk by the loader.
 *
 * The loader returns raw text only. Interpreting the content (parsing kernel
 * documents, extracting knowledge) is explicitly out of scope for the runtime.
 */
export interface LoadedDocument {
  /** Path requested by the caller, relative to the loader base directory. */
  readonly relativePath: string;

  /** Absolute path that was actually read. */
  readonly absolutePath: string;

  /** Raw UTF-8 file contents. */
  readonly content: string;
}

/**
 * Immutable record describing a single tracked task and its state history.
 */
export interface TaskRecord {
  /** Unique task identifier generated by the workflow. */
  readonly id: RuntimeId;

  /** Work package the task represents. */
  readonly workPackageId: RuntimeId;

  /** Current lifecycle state. */
  readonly state: TaskState;

  /** Ordered list of every state the task has occupied. */
  readonly history: readonly TaskState[];
}

/**
 * A single observable runtime event.
 *
 * Events are plain data so callers may log, persist, or ignore them. The
 * `sequence` field provides deterministic ordering without wall-clock time.
 */
export interface RuntimeEvent {
  /** Monotonic position of the event within a run. */
  readonly sequence: number;

  /** Lifecycle state associated with the event. */
  readonly state: TaskState;

  /** Human-readable description of the structural step that occurred. */
  readonly message: string;
}

/**
 * Final, immutable report describing one runtime execution.
 */
export interface ExecutionReport {
  /** Unique report identifier generated by the runtime. */
  readonly id: RuntimeId;

  /** Work package that was executed. */
  readonly workPackageId: RuntimeId;

  /** Agent that received the work package. */
  readonly assignedAgentId: RuntimeId;

  /** Terminal state of the execution. */
  readonly finalState: Extract<TaskState, "completed" | "failed">;

  /** Ordered events emitted during the execution. */
  readonly events: readonly RuntimeEvent[];
}

/**
 * Port implemented by the loader module.
 *
 * Depending on this interface (rather than the concrete class) lets the
 * orchestrator, tests, and future callers substitute alternative loaders.
 */
export interface DocumentLoaderPort {
  /** Load a single document relative to the loader base directory. */
  load(relativePath: string): Promise<LoadedDocument>;

  /** Load several documents, preserving input order. */
  loadMany(relativePaths: readonly string[]): Promise<readonly LoadedDocument[]>;
}

/**
 * Port implemented by the dispatcher module.
 *
 * The dispatcher decides which agent receives a work package. It performs
 * structural routing only and never executes the chosen agent.
 */
export interface DispatcherPort {
  /** Select an agent for the given work package from the supplied candidates. */
  dispatch(
    workPackage: WorkPackage,
    agents: readonly AgentDescriptor[]
  ): AgentAssignment;
}

/**
 * Port implemented by the workflow module.
 *
 * The workflow is an in-memory state tracker. It owns task-state transitions
 * and rejects illegal transitions, but performs no work itself.
 */
export interface WorkflowPort {
  /** Begin tracking a task for a work package in the `pending` state. */
  register(workPackageId: RuntimeId): TaskRecord;

  /** Move a tracked task to the next state, if the transition is legal. */
  transition(taskId: RuntimeId, next: TaskState): TaskRecord;

  /** Read the current record for a task, if it exists. */
  get(taskId: RuntimeId): TaskRecord | undefined;

  /** Snapshot every tracked task. */
  all(): readonly TaskRecord[];
}

/**
 * Port implemented by the execution-report module.
 *
 * The builder accumulates ordered events and produces an immutable report. It
 * is deliberately mutable during accumulation and immutable once built.
 */
export interface ExecutionReportBuilderPort {
  /** Append an event, returning the builder for fluent chaining. */
  record(state: TaskState, message: string): this;

  /** Produce the final report for a completed or failed execution. */
  build(
    workPackageId: RuntimeId,
    assignedAgentId: RuntimeId,
    finalState: Extract<TaskState, "completed" | "failed">
  ): ExecutionReport;
}
